const translations = {

    ru: {
        lang: "Язык",
        services: "Услуги",
        stages: "Этапы строительства",
        advantages: "Преимущества",
        projects: "Проекты",
        contacts: "Контакты",
        question: "Есть вопросы?",
        contact: "Свяжитесь с нами",
        name: "Ваше имя",
        email: "Ваш email",
        phone: "Телефон",
        subject: "Тема",
        message: "Ваше сообщение",
        send: "Отправить",
        servicesTitle: "Наши услуги",
        servicesDesc: "Мы предоставляем комплексные услуги в сфере строительства.",
        service1: "Проектирование",
        service2: "Инжиниринг",
        service3: "Строительство",
        service1Desc: "Мы создаем современные и эффективные проекты домов.",
        learnMore: "Подробнее",
        service2Desc: "Комплексные инженерные решения.",
        service3Desc: "Полный цикл строительства домов.",
        stagesTitle: "Этапы строительства",
        stagesDesc: "Полный цикл строительства дома",
        stage1: "Подготовка участка и фундамент",
        stage1Desc: "Выравнивание участка, земляные работы",
        stage2: "Проектирование и инжиниринг",
        stage2Desc: "Архитектура и расчёты",
        stage3: "Производство SIP панелей",
        stage3Desc: "Изготовление элементов дома",
        stage4: "Доставка и сборка",
        stage4Desc: "Монтаж конструкции",
        stage5: "Кровля и фасад",
        stage5Desc: "Внешняя отделка",
        stage6: "Инженерные системы",
        stage6Desc: "Электрика и коммуникации",
        stage7: "Внутренняя отделка",
        stage7Desc: "Финишные работы",
        stage8: "Проверка и сдача",
        stage8Desc: "Контроль качества",
        stage9: "Сдача и заселение",
        stage9Desc: "Передача дома клиенту",
        advantagesTitle: "Наши преимущества",
        advantagesDesc: "Почему клиенты выбирают Eco Haus Meister",
        adv1: "Полный цикл строительства",
        adv1Desc: "От проектирования до сдачи объекта под ключ",
        adv2: "Быстрое строительство",
        adv2Desc: "Современные технологии позволяют сократить сроки",
        adv3: "Экологичные материалы",
        adv3Desc: "Безопасные и энергоэффективные решения",
        adv4: "Оптимальная стоимость",
        adv4Desc: "Лучшее соотношение цены и качества",
        adv5: "Современные технологии",
        adv5Desc: "Используем SIP и инновационные решения",
        adv6: "Индивидуальный подход",
        adv6Desc: "Учитываем все пожелания клиента"
    },

    en: {
        lang: "Language",
        services: "Services",
        stages: "Construction Stages",
        advantages: "Advantages",
        projects: "Projects",
        contacts: "Contacts",
        question: "Any questions?",
        contact: "Contact Us",
        name: "Your name",
        email: "Your email",
        phone: "Phone",
        subject: "Subject",
        message: "Your message",
        send: "Send",
        servicesTitle: "Our Services",
        servicesDesc: "We provide comprehensive construction services.",
        service1: "Design",
        service2: "Engineering",
        service3: "Construction",
        service1Desc: "We create modern and efficient house designs.",
        learnMore: "Learn more",
        service2Desc: "Engineering solutions.",
        service3Desc: "Full construction cycle.",
        stagesTitle: "Construction Stages",
        stagesDesc: "Complete house construction process from idea to move-in",
        stage1: "Site preparation & foundation",
        stage1Desc: "Land leveling, excavation, concrete foundation",
        stage2: "Design & engineering",
        stage2Desc: "Architectural design, calculations, approvals",
        stage3: "SIP panel production",
        stage3Desc: "Manufacturing walls, roof and floor panels",
        stage4: "Delivery & assembly",
        stage4Desc: "On-site house structure installation",
        stage5: "Roof & exterior",
        stage5Desc: "Roofing, windows and facade installation",
        stage6: "Engineering systems",
        stage6Desc: "Electrical, heating and plumbing systems",
        stage7: "Interior finishing",
        stage7Desc: "Walls, flooring, painting and fixtures",
        stage8: "Testing & inspection",
        stage8Desc: "System testing and final inspection",
        stage9: "Handover & move-in",
        stage9Desc: "Keys delivery and documentation",
        advantagesTitle: "Our Advantages",
        advantagesDesc: "Why clients choose Eco Haus Meister",
        adv1: "Full construction cycle",
        adv1Desc: "From design to turnkey delivery",
        adv2: "Fast construction",
        adv2Desc: "Modern technologies reduce timelines",
        adv3: "Eco-friendly materials",
        adv3Desc: "Safe and energy-efficient solutions",
        adv4: "Optimal pricing",
        adv4Desc: "Best price-quality ratio",
        adv5: "Modern technologies",
        adv5Desc: "We use SIP and innovative solutions",
        adv6: "Individual approach",
        adv6Desc: "We consider all client needs"
    },

    ro: {
        lang: "Limbă",
        services: "Servicii",
        stages: "Etapele construcției",
        advantages: "Avantaje",
        projects: "Proiecte",
        contacts: "Contacte",
        question: "Aveți întrebări?",
        contact: "Contactați-ne",
        name: "Numele dvs.",
        email: "Emailul dvs.",
        phone: "Telefon",
        subject: "Subiect",
        message: "Mesajul dvs.",
        send: "Trimite",
        servicesTitle: "Serviciile noastre",
        servicesDesc: "Oferim servicii complete în domeniul construcțiilor.",
        service1: "Proiectare",
        service2: "Inginerie",
        service3: "Construcție",
        service1Desc: "Creăm proiecte moderne și eficiente.",
        learnMore: "Detalii",
        service2Desc: "Soluții inginerești complete.",
        service3Desc: "Ciclu complet de construcție.",
        stagesTitle: "Etapele construcției",
        stagesDesc: "Proces complet de construcție a casei de la idee până la mutare",
        stage1: "Pregătirea terenului și fundația",
        stage1Desc: "Nivelare, excavare, fundație din beton",
        stage2: "Proiectare și inginerie",
        stage2Desc: "Proiect arhitectural și calcule",
        stage3: "Producția panourilor SIP",
        stage3Desc: "Fabricarea pereților, acoperișului și podelei",
        stage4: "Livrare și montaj",
        stage4Desc: "Asamblarea structurii pe șantier",
        stage5: "Acoperiș și exterior",
        stage5Desc: "Montaj acoperiș, ferestre și fațadă",
        stage6: "Sisteme inginerești",
        stage6Desc: "Electricitate, încălzire și apă",
        stage7: "Finisaje interioare",
        stage7Desc: "Pereți, podele, vopsire și echipamente",
        stage8: "Testare și inspecție",
        stage8Desc: "Verificarea sistemelor",
        stage9: "Predare și mutare",
        stage9Desc: "Predarea cheilor și documentelor",
        advantagesTitle: "Avantajele noastre",
        advantagesDesc: "De ce clienții aleg Eco Haus Meister",
        adv1: "Ciclu complet de construcție",
        adv1Desc: "De la proiectare până la predare",
        adv2: "Construcție rapidă",
        adv2Desc: "Tehnologiile moderne reduc timpul",
        adv3: "Materiale ecologice",
        adv3Desc: "Soluții sigure și eficiente energetic",
        adv4: "Cost optim",
        adv4Desc: "Cel mai bun raport calitate-preț",
        adv5: "Tehnologii moderne",
        adv5Desc: "Folosim SIP și soluții inovatoare",
        adv6: "Abordare individuală",
        adv6Desc: "Ținem cont de toate cerințele clientului"
    },

    de: {
        lang: "Sprache",
        services: "Dienstleistungen",
        stages: "Bauphasen",
        advantages: "Vorteile",
        projects: "Projekte",
        contacts: "Kontakte",
        question: "Haben Sie Fragen?",
        contact: "Kontaktieren Sie uns",
        name: "Ihr Name",
        email: "Ihre E-Mail",
        phone: "Telefon",
        subject: "Betreff",
        message: "Ihre Nachricht",
        send: "Senden",
        servicesTitle: "Unsere Dienstleistungen",
        servicesDesc: "Wir bieten umfassende Bauleistungen an.",
        service1: "Planung",
        service2: "Ingenieurwesen",
        service3: "Bau",
        service1Desc: "Wir erstellen moderne und effiziente Hausprojekte.",
        learnMore: "Mehr erfahren",
        service2Desc: "Ingenieurlösungen.",
        service3Desc: "Vollständiger Bauzyklus.",
        stagesTitle: "Bauphasen",
        stagesDesc: "Kompletter Bauprozess vom Konzept bis zum Einzug",
        stage1: "Grundstücksvorbereitung & Fundament",
        stage1Desc: "Nivellierung, Aushub, Betonfundament",
        stage2: "Planung & Ingenieurwesen",
        stage2Desc: "Architektur und Berechnungen",
        stage3: "SIP-Paneele Produktion",
        stage3Desc: "Herstellung von Wänden, Dach und Boden",
        stage4: "Lieferung & Montage",
        stage4Desc: "Montage der Hausstruktur vor Ort",
        stage5: "Dach & Außenarbeiten",
        stage5Desc: "Dach, Fenster und Fassade",
        stage6: "Technische Systeme",
        stage6Desc: "Elektrik, Heizung und Sanitär",
        stage7: "Innenausbau",
        stage7Desc: "Wände, Böden, Anstrich und Ausstattung",
        stage8: "Prüfung & Inspektion",
        stage8Desc: "Systemtests und Kontrolle",
        stage9: "Übergabe & Einzug",
        stage9Desc: "Schlüsselübergabe und Dokumente",
        advantagesTitle: "Unsere Vorteile",
        advantagesDesc: "Warum Kunden Eco Haus Meister wählen",
        adv1: "Kompletter Bauzyklus",
        adv1Desc: "Von der Planung bis zur schlüsselfertigen Übergabe",
        adv2: "Schnelle Bauzeit",
        adv2Desc: "Moderne Technologien verkürzen die Bauzeit",
        adv3: "Umweltfreundliche Materialien",
        adv3Desc: "Sichere und energieeffiziente Lösungen",
        adv4: "Optimale Kosten",
        adv4Desc: "Bestes Preis-Leistungs-Verhältnis",
        adv5: "Moderne Technologien",
        adv5Desc: "Wir nutzen SIP und innovative Lösungen",
        adv6: "Individuelle Herangehensweise",
        adv6Desc: "Wir berücksichtigen alle Kundenwünsche"
    }

};

function toggleLang() {
    document.getElementById("langMenu").classList.toggle("hidden");
}

function setLang(lang) {

    document.getElementById("currentLang").innerText = translations[lang].lang;

    const elements = document.querySelectorAll("[data-key]");

    elements.forEach(el => {
        const key = el.getAttribute("data-key");

        if (translations[lang][key]) {
        if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
            el.placeholder = translations[lang][key];
        } else {
            el.innerText = translations[lang][key];
        }
    }
    });

    document.getElementById("langMenu").classList.add("hidden");

    localStorage.setItem("lang", lang);
}

function openModal(id) {
    document.getElementById(id).classList.remove("hidden");
    document.getElementById(id).classList.add("flex");
}

function closeModal(id) {
    document.getElementById(id).classList.add("hidden");
}