const translations = {
 
    ru: {
        lang: "Язык",
        services: "Услуги",
        stages: "Этапы строительства",
        stagesDesc: "Полный цикл строительства дома от идеи до заселения",
        advantages: "Преимущества",
        projects: "Проекты",
        contacts: "Контакты",
        question: "Есть вопросы?",
        contact: "Свяжитесь с нами",
        name: "Ваше имя",
        email: "Ваш email",
        phone: "Телефон",
        subject: "Тема",
        message: "Ваше сообщение",
        send: "Отправить",
        servicesTitle: "Наши услуги",
        servicesDesc: "Мы предоставляем комплексные услуги в сфере строительства.",
        servicesHeroDesc: "Комплексные решения — от проекта до готового дома под ключ",
        servicesIntro: "Eco Meister Haus предоставляет полный спектр услуг в сфере строительства энергоэффективных домов. Мы работаем по технологии SIP и берём на себя весь процесс — от архитектурного проекта до финальной отделки и сдачи объекта.",
        service1: "Проектирование",
        service1Short: "Индивидуальный архитектурный проект под ваш участок и бюджет",
        service2: "Инжиниринг",
        service2Short: "Электрика, отопление, вентиляция и водоснабжение — полный инженерный комплекс",
        service3: "Строительство",
        service3Short: "Возводим дом от фундамента до ключей — быстро, надёжно, по фиксированной цене",
        service1Desc: "Мы создаем современные и эффективные проекты домов.",
        learnMore: "Подробнее",
        service2Desc: "Комплексные инженерные решения.",
        service3Desc: "Полный цикл строительства домов.",
        faqTitle: "Частые вопросы",
        faq1Q: "Сколько времени занимает строительство дома?",
        faq1A: "Дом по технологии SIP строится значительно быстрее традиционного. В среднем монтаж коробки занимает 2–4 недели, полный цикл строительства под ключ — от 3 до 6 месяцев в зависимости от сложности проекта.",
        faq2Q: "Можно ли изменить проект в процессе строительства?",
        faq2A: "Небольшие изменения возможны до начала производства SIP-панелей. После запуска в производство корректировки ограничены. Поэтому мы уделяем особое внимание финальному согласованию проекта.",
        faq3Q: "Даёте ли вы гарантию на построенный дом?",
        faq3A: "Да. Мы предоставляем гарантию на конструктив и все выполненные работы. Детальные условия обсуждаются при заключении договора.",
        servicesCtaTitle: "Нужна консультация?",
        servicesCtaDesc: "Расскажите о вашем проекте — мы ответим на все вопросы и подготовим предварительный расчёт",
        contactTitle: "Свяжитесь с нами",
        formTitle: "Напишите нам",
        mapTitle: "Где нас найти",
        mapPlaceholder: "Карта будет добавлена здесь",
        nextStepTitle: "Как мы работаем с вашим запросом",
        step1Title: "Вы пишете или звоните",
        step1Desc: "Заполните форму или позвоните напрямую — мы ответим в течение 24 часов",
        step2Title: "Мы обсуждаем проект",
        step2Desc: "Выясняем ваши пожелания, размер участка и бюджет. Это бесплатно и ни к чему не обязывает",
        step3Title: "Вы получаете расчёт",
        step3Desc: "Подготавливаем предварительную смету и план работ под ваш проект",
        stagesTitle: "Этапы строительства",
        stage1: "Подготовка участка и фундамент",
        stage1Desc: "Выравнивание участка, земляные работы",
        stage2: "Проектирование и инжиниринг",
        stage2Desc: "Архитектура и расчёты",
        stage3: "Производство SIP панелей",
        stage3Desc: "Изготовление элементов дома",
        stage4: "Доставка и сборка",
        stage4Desc: "Монтаж конструкции",
        stage5: "Кровля и фасад",
        stage5Desc: "Внешняя отделка",
        stage6: "Инженерные системы",
        stage6Desc: "Электрика и коммуникации",
        stage7: "Внутренняя отделка",
        stage7Desc: "Финишные работы",
        stage8: "Проверка и сдача",
        stage8Desc: "Контроль качества",
        stage9: "Сдача и заселение",
        stage9Desc: "Передача дома клиенту",
        ctaStagesTitle: "Готовы начать строительство?",
        ctaStagesDesc: "Свяжитесь с нами — обсудим ваш проект и рассчитаем стоимость",
        ctaContact: "Получить консультацию",
        ctaProjects: "Смотреть проекты",
        ctaProjectsTitle: "Хотите такой же дом?",
        ctaProjectsDesc: "Обсудим ваш проект и подберём оптимальное решение",
        advantagesTitle: "Наши преимущества",
        advantagesDesc: "Почему клиенты выбирают Eco Meister Haus",
        advantagesIntro: "Eco Meister Haus строит энергоэффективные дома по технологии SIP в соответствии с европейскими стандартами. Мы берём полную ответственность за каждый этап — от проекта до ключей — и предлагаем прозрачные условия без скрытых доплат.",
        adv1: "Полный цикл строительства",
        adv1Desc: "От проектирования до сдачи объекта под ключ",
        adv2: "Быстрое строительство",
        adv2Desc: "Современные технологии позволяют сократить сроки в 2–3 раза",
        adv3: "Экологичные материалы",
        adv3Desc: "Сертифицированные материалы без вредных выбросов",
        adv4: "Оптимальная стоимость",
        adv4Desc: "Лучшее соотношение цены и качества на рынке",
        adv5: "Современные технологии",
        adv5Desc: "SIP-панели и инновационные инженерные решения",
        adv6: "Индивидуальный подход",
        adv6Desc: "Учитываем все пожелания клиента без исключений",
        adv7: "Энергоэффективность",
        adv7Desc: "Класс A+ — затраты на отопление ниже до 60%",
        adv8: "Европейские стандарты",
        adv8Desc: "Строим по европейским нормам и используем сертифицированные материалы",
        advFaqTitle: "Частые вопросы",
        advFaq1Q: "Насколько прочен SIP-дом по сравнению с кирпичным?",
        advFaq1A: "SIP-панели выдерживают нагрузки, сопоставимые с кирпичными стенами, а в ряде тестов на сжатие и сейсмостойкость превосходят их. Конструкция проверена десятилетиями эксплуатации в Европе и Северной Америке.",
        advFaq2Q: "Насколько SIP-дом энергоэффективен зимой?",
        advFaq2A: "Благодаря монолитному слою утеплителя без мостиков холода дом класса A+ потребляет на 50–60% меньше энергии на отопление, чем традиционный дом аналогичной площади.",
        advFaq3Q: "Соответствует ли строительство европейским нормам?",
        advFaq3A: "Да. Мы используем сертифицированные материалы и работаем в соответствии с европейскими строительными стандартами. Все панели проходят контроль качества до поставки на объект.",
        advCtaTitle: "Убедились в наших преимуществах?",
        advCtaDesc: "Свяжитесь с нами — обсудим ваш проект и покажем, как эти преимущества работают именно для вас",
        projectsTitle: "Наши проекты",
        projectsDesc: "Ознакомьтесь с нашими реализованными проектами домов.",
        catModern: "Современные",
        catCountry: "Загородные",
        catMinimal: "Минимализм",
        catModernTitle: "Современные дома",
        catCountryTitle: "Загородные дома",
        catMinimalTitle: "Минималистичные дома",
        project1: "Современный дом",
        project1Desc: "Энергоэффективный дом с современным дизайном.",
        project1Full: "Полностью энергоэффективный дом с использованием SIP-панелей.",
        project2: "Загородный коттедж",
        project2Desc: "Уютный дом для семьи за городом.",
        project2Full: "Просторный коттедж с террасой и панорамными окнами.",
        project3: "Минималистичный дом",
        project3Desc: "Стильный дом в современном минимализме.",
        project3Full: "Современный минимализм с функциональной планировкой.",
        viewProject: "Смотреть",
        heroTitle1: "Строим быстрее, проще и эффективнее",
        heroTitle2: "Современные SIP технологии",
        heroTitle3: "Надежные и энергоэффективные дома",
        whyTitle: "Почему Eco Haus Meister",
        whyDesc: "Четыре причины, по которым нам доверяют строительство своего дома",
        why1Title: "Быстро",
        why1Desc: "Дом под ключ за 3–6 месяцев благодаря SIP-технологии",
        why2Title: "Экологично",
        why2Desc: "Только сертифицированные материалы без вредных выбросов",
        why3Title: "По евростандартам",
        why3Desc: "Строим в соответствии с европейскими нормами энергоэффективности",
        why4Title: "Индивидуально",
        why4Desc: "Каждый проект — под конкретного клиента, участок и бюджет",
        sipBadge: "Технология будущего",
        sipTitle: "SIP Premium Class — дома нового поколения",
        sipDesc: "SIP-панели (Structural Insulated Panels) — это конструкция из двух плит OSB и слоя пенополистирола между ними. Результат: дом, который держит тепло зимой, прохладу летом и строится в разы быстрее кирпичного.",
        sipPoint1: "Класс энергоэффективности A+ — затраты на отопление до −60%",
        sipPoint2: "Монтаж коробки дома — от 2 до 4 недель",
        sipPoint3: "Срок службы — более 50 лет без потери свойств",
        sipPoint4: "Сертифицировано по европейским стандартам",
        sipCta: "Узнать об этапах строительства",
        sipStat1: "затраты на отопление",
        sipStat2: "быстрее кирпичного дома",
        sipStat3: "лет срок службы",
        sipStat4: "класс энергоэффективности",
        materialsTitle: "Материалы и технологии",
        materialsDesc: "Используем только то, что проверено европейской практикой",
        mat1Title: "OSB + пенополистирол",
        mat1Desc: "Сердце SIP-панели — высококачественный пенополистирол между двумя плитами OSB. Обеспечивает тепло, жёсткость и лёгкость конструкции.",
        mat2Title: "Вентиляция и климат",
        mat2Desc: "Рекуперация тепла, приточно-вытяжная вентиляция и современные системы климат-контроля для комфортного микроклимата круглый год.",
        mat3Title: "Фасад и кровля",
        mat3Desc: "Долговечные фасадные системы, металлочерепица и мягкая кровля европейских производителей. Защита от влаги, огня и ультрафиолета.",
        stagesPreviewTitle: "Как мы строим",
        stagesPreviewDesc: "От первого звонка до передачи ключей — понятный процесс без сюрпризов",
        stagesPrev1: "Участок и фундамент",
        stagesPrev2: "Проект и панели",
        stagesPrev3: "Сборка и кровля",
        stagesPrev4: "Отделка и заселение",
        stagesPreviewCta: "Все этапы подробно →",
        projectsPreviewTitle: "Наши проекты",
        projectsPreviewDesc: "Реализованные дома — от компактных до просторных",
        projectsPreviewCta: "Смотреть все проекты →",
        designBadge: "Только для вас",
        designTitle: "Индивидуальный дизайн под ваш стиль жизни",
        designDesc: "Мы не продаём типовые коробки. Каждый дом проектируется под конкретного человека — с учётом участка, семьи, привычек и бюджета. Вы выбираете планировку, фасад, материалы отделки и стиль интерьера.",
        designPoint1: "Свободная планировка",
        designPoint2: "Выбор фасада и кровли",
        designPoint3: "Любой стиль интерьера",
        designPoint4: "Под ваш участок и рельеф",
        designCta: "Обсудить проект",
        ctaBadge: "Начните сегодня",
        ctaMainTitle: "Готовы построить дом своей мечты?",
        ctaMainDesc: "Расскажите нам о вашем проекте — мы рассчитаем стоимость, предложим решение и ответим на все вопросы. Бесплатно и без обязательств.",
        ctaMainBtn1: "Получить консультацию",
        ctaMainBtn2: "Смотреть проекты",
        aboutTitle: "О нашей компании",
        aboutDesc: "Мы специализируемся на строительстве энергоэффективных домов по технологии SIP.",
        about: "О компании",
        aboutHeroTitle: "О компании",
        aboutHeroDesc: "Строим современные, надёжные и энергоэффективные дома по европейским стандартам",
        aboutCompanyTitle: "Кто мы",
        aboutCompanyText1: "Eco Meister Haus — это команда профессионалов в сфере строительства энергоэффективных домов. Мы работаем по технологии SIP и применяем современные европейские стандарты на каждом этапе — от проектирования до передачи ключей.",
        aboutCompanyText2: "Наша цель — строить дома, в которых комфортно жить и выгодно содержать. Тёплые зимой, прохладные летом, долговечные и красивые.",
        aboutValuesTitle: "Наши принципы",
        aboutValuesDesc: "Качество, экологичность и европейские стандарты — в каждом проекте",
        val1Title: "Экологичность",
        val1Desc: "Используем только безопасные, сертифицированные материалы без вредных выбросов",
        val2Title: "Качество",
        val2Desc: "Каждый этап проходит контроль качества. Мы не сдаём объект, пока не убедимся в его надёжности",
        val3Title: "Европейские стандарты",
        val3Desc: "Строим в соответствии с европейскими нормами энергоэффективности и строительными регламентами",
        aboutApproachTitle: "Наш подход",
        aboutApproachDesc: "Как мы работаем с каждым клиентом",
        approach1Title: "Слушаем и понимаем",
        approach1Desc: "Начинаем с детального разговора о ваших пожеланиях, бюджете и сроках. Никаких шаблонных решений.",
        approach2Title: "Проектируем под вас",
        approach2Desc: "Разрабатываем индивидуальный проект с учётом вашего участка, климата и стиля жизни.",
        approach3Title: "Строим прозрачно",
        approach3Desc: "Вы в курсе каждого этапа. Регулярные отчёты, фото с объекта, фиксированная смета без скрытых доплат.",
        approach4Title: "Сдаём под ключ",
        approach4Desc: "Передаём готовый дом с полным пакетом документов и гарантией на выполненные работы.",
        aboutTechTitle: "Технологии и материалы",
        aboutTechText1: "В основе наших домов — технология SIP (Structural Insulated Panels). Это сэндвич-панели из OSB и пенополистирола, которые обеспечивают высокую теплоизоляцию, прочность и скорость строительства.",
        aboutTechText2: "Дом на SIP возводится в несколько раз быстрее кирпичного, при этом превосходит его по энергоэффективности. Затраты на отопление снижаются до 60%.",
        techStat1: "затраты на отопление",
        techStat2: "быстрее кирпичного дома",
        techStat3: "лет срок службы",
        techStat4: "класс энергоэффективности",
        aboutCtaTitle: "Готовы построить дом вашей мечты?",
        aboutCtaDesc: "Расскажите нам о вашем проекте — мы подберём оптимальное решение и рассчитаем стоимость",
        bank: "БАНКОВСКИЕ ДАННЫЕ",
        social: "СОЦИАЛЬНЫЕ СЕТИ",
        advIntro: "Eco Meister Haus строит энергоэффективные дома по технологии SIP в соответствии с европейскими стандартами. Мы берём полную ответственность за каждый этап — от проекта до ключей — и предлагаем прозрачные условия без скрытых доплат.",
        advFaqTitle: "Частые вопросы",
        advFaq1Q: "Насколько прочен SIP-дом по сравнению с кирпичным?",
        advFaq1A: "SIP-панели выдерживают нагрузки, сопоставимые с кирпичными стенами, а в ряде тестов на сжатие и сейсмостойкость превосходят их. Конструкция проверена десятилетиями эксплуатации в Европе и Северной Америке.",
        advFaq2Q: "Насколько SIP-дом энергоэффективен зимой?",
        advFaq2A: "Благодаря монолитному слою утеплителя без мостиков холода дом класса A+ потребляет на 50–60% меньше энергии на отопление, чем традиционный дом аналогичной площади.",
        advFaq3Q: "Соответствует ли строительство европейским нормам?",
        advFaq3A: "Да. Мы используем сертифицированные материалы и работаем в соответствии с европейскими строительными стандартами. Все панели проходят контроль качества до поставки на объект.",
        advCtaTitle: "Убедились в наших преимуществах?",
        advCtaDesc: "Свяжитесь с нами — обсудим ваш проект и покажем, как эти преимущества работают именно для вас",
        contactDetailsTitle: "КОНТАКТНЫЕ ДАННЫЕ",
    },
 
    en: {
        lang: "Language",
        services: "Services",
        stages: "Construction Stages",
        stagesDesc: "Complete house construction process from idea to move-in",
        advantages: "Advantages",
        projects: "Projects",
        contacts: "Contacts",
        question: "Any questions?",
        contact: "Contact Us",
        name: "Your name",
        email: "Your email",
        phone: "Phone",
        subject: "Subject",
        message: "Your message",
        send: "Send",
        servicesTitle: "Our Services",
        servicesDesc: "We provide comprehensive construction services.",
        servicesHeroDesc: "Comprehensive solutions — from design to turnkey home",
        servicesIntro: "Eco Meister Haus provides a full range of services in energy-efficient home construction. We work with SIP technology and take care of the entire process — from architectural design to final finishing and handover.",
        service1: "Design",
        service1Short: "Individual architectural project tailored to your plot and budget",
        service2: "Engineering",
        service2Short: "Electrical, heating, ventilation and water supply — full engineering complex",
        service3: "Construction",
        service3Short: "We build from foundation to keys — fast, reliable, at a fixed price",
        service1Desc: "We create modern and efficient house designs.",
        learnMore: "Learn more",
        service2Desc: "Engineering solutions.",
        service3Desc: "Full construction cycle.",
        faqTitle: "Frequently Asked Questions",
        faq1Q: "How long does it take to build a house?",
        faq1A: "A SIP house is built significantly faster than a traditional one. On average, the shell takes 2–4 weeks, and the full turnkey construction cycle takes 3 to 6 months depending on the complexity of the project.",
        faq2Q: "Can the project be changed during construction?",
        faq2A: "Minor changes are possible before SIP panel production begins. After production starts, adjustments are limited. That's why we pay special attention to the final project approval.",
        faq3Q: "Do you provide a warranty on the built house?",
        faq3A: "Yes. We provide a warranty on the structure and all completed work. Detailed terms are discussed when signing the contract.",
        servicesCtaTitle: "Need a consultation?",
        servicesCtaDesc: "Tell us about your project — we'll answer all questions and prepare a preliminary estimate",
        contactTitle: "Contact Us",
        contactDetailsTitle: "CONTACT DETAILS",
        formTitle: "Write to us",
        mapTitle: "Where to find us",
        mapPlaceholder: "Map will be added here",
        nextStepTitle: "How we handle your request",
        step1Title: "You write or call",
        step1Desc: "Fill out the form or call directly — we'll respond within 24 hours",
        step2Title: "We discuss the project",
        step2Desc: "We clarify your wishes, plot size and budget. This is free and non-binding",
        step3Title: "You receive an estimate",
        step3Desc: "We prepare a preliminary budget and work plan for your project",
        stagesTitle: "Construction Stages",
        stage1: "Site preparation & foundation",
        stage1Desc: "Land leveling, excavation, concrete foundation",
        stage2: "Design & engineering",
        stage2Desc: "Architectural design, calculations, approvals",
        stage3: "SIP panel production",
        stage3Desc: "Manufacturing walls, roof and floor panels",
        stage4: "Delivery & assembly",
        stage4Desc: "On-site house structure installation",
        stage5: "Roof & exterior",
        stage5Desc: "Roofing, windows and facade installation",
        stage6: "Engineering systems",
        stage6Desc: "Electrical, heating and plumbing systems",
        stage7: "Interior finishing",
        stage7Desc: "Walls, flooring, painting and fixtures",
        stage8: "Testing & inspection",
        stage8Desc: "System testing and final inspection",
        stage9: "Handover & move-in",
        stage9Desc: "Keys delivery and documentation",
        ctaStagesTitle: "Ready to start building?",
        ctaStagesDesc: "Contact us — we'll discuss your project and calculate the cost",
        ctaContact: "Get a consultation",
        ctaProjects: "View projects",
        ctaProjectsTitle: "Want a similar home?",
        ctaProjectsDesc: "We'll discuss your project and find the best solution",
        advantagesTitle: "Our Advantages",
        advantagesDesc: "Why clients choose Eco Haus Meister",
        adv1: "Full construction cycle",
        adv1Desc: "From design to turnkey delivery",
        adv2: "Fast construction",
        adv2Desc: "Modern technologies reduce timelines",
        adv3: "Eco-friendly materials",
        adv3Desc: "Safe and energy-efficient solutions",
        adv4: "Optimal pricing",
        adv4Desc: "Best price-quality ratio",
        adv5: "Modern technologies",
        adv5Desc: "We use SIP and innovative solutions",
        adv6: "Individual approach",
        adv6Desc: "We consider all client needs",
        projectsTitle: "Our Projects",
        projectsDesc: "Explore our completed house construction projects.",
        catModern: "Modern",
        catCountry: "Country",
        catMinimal: "Minimalist",
        catModernTitle: "Modern homes",
        catCountryTitle: "Country homes",
        catMinimalTitle: "Minimalist homes",
        project1: "Modern House",
        project1Desc: "Energy-efficient house with modern design.",
        project1Full: "Fully energy-efficient house built using SIP panels.",
        project2: "Country Cottage",
        project2Desc: "Cozy house for a family outside the city.",
        project2Full: "Spacious cottage with terrace and panoramic windows.",
        project3: "Minimalist House",
        project3Desc: "Stylish house in modern minimalist design.",
        project3Full: "Modern minimalism with a functional layout.",
        viewProject: "View",
        heroTitle1: "Build faster, easier and more efficiently",
        heroTitle2: "Modern SIP technologies",
        heroTitle3: "Reliable and energy-efficient homes",
        whyTitle: "Why Eco Haus Meister",
        whyDesc: "Four reasons why people trust us to build their home",
        why1Title: "Fast",
        why1Desc: "Turnkey home in 3–6 months thanks to SIP technology",
        why2Title: "Eco-friendly",
        why2Desc: "Only certified materials with no harmful emissions",
        why3Title: "European standards",
        why3Desc: "We build to European energy efficiency norms",
        why4Title: "Individual",
        why4Desc: "Every project is tailored to the client, plot and budget",
        sipBadge: "Technology of the future",
        sipTitle: "SIP Premium Class — next generation homes",
        sipDesc: "SIP panels (Structural Insulated Panels) are a construction of two OSB boards with a polystyrene foam layer between them. The result: a home that stays warm in winter, cool in summer, and is built several times faster than brick.",
        sipPoint1: "Energy efficiency class A+ — heating costs reduced by up to 60%",
        sipPoint2: "House frame installation — from 2 to 4 weeks",
        sipPoint3: "Service life — over 50 years without loss of properties",
        sipPoint4: "Certified to European standards",
        sipCta: "Learn about construction stages",
        sipStat1: "heating cost reduction",
        sipStat2: "faster than brick homes",
        sipStat3: "years service life",
        sipStat4: "energy efficiency class",
        materialsTitle: "Materials and technologies",
        materialsDesc: "We use only what has been proven by European practice",
        mat1Title: "OSB + polystyrene foam",
        mat1Desc: "The heart of the SIP panel — high-quality polystyrene foam between two OSB boards. Provides warmth, rigidity and light weight.",
        mat2Title: "Ventilation and climate",
        mat2Desc: "Heat recovery, supply-exhaust ventilation and modern climate control systems for a comfortable microclimate all year round.",
        mat3Title: "Facade and roofing",
        mat3Desc: "Durable facade systems, metal tiles and soft roofing from European manufacturers. Protection against moisture, fire and UV.",
        stagesPreviewTitle: "How we build",
        stagesPreviewDesc: "From the first call to key handover — a clear process with no surprises",
        stagesPrev1: "Plot and foundation",
        stagesPrev2: "Design and panels",
        stagesPrev3: "Assembly and roofing",
        stagesPrev4: "Finishing and move-in",
        stagesPreviewCta: "All stages in detail →",
        projectsPreviewTitle: "Our projects",
        projectsPreviewDesc: "Completed homes — from compact to spacious",
        projectsPreviewCta: "View all projects →",
        designBadge: "Just for you",
        designTitle: "Individual design for your lifestyle",
        designDesc: "We don't sell standard boxes. Every home is designed for a specific person — considering the plot, family, habits and budget. You choose the layout, facade, finishing materials and interior style.",
        designPoint1: "Free layout",
        designPoint2: "Choice of facade and roof",
        designPoint3: "Any interior style",
        designPoint4: "Tailored to your plot and terrain",
        designCta: "Discuss a project",
        ctaBadge: "Start today",
        ctaMainTitle: "Ready to build your dream home?",
        ctaMainDesc: "Tell us about your project — we'll calculate the cost, suggest a solution and answer all questions. Free and without obligation.",
        ctaMainBtn1: "Get a consultation",
        ctaMainBtn2: "View projects",
        aboutTitle: "About our company",
        aboutDesc: "We specialize in building energy-efficient homes using SIP technology.",
        about: "About Us",
        aboutHeroTitle: "About Us",
        aboutHeroDesc: "Building modern, reliable and energy-efficient homes to European standards",
        aboutCompanyTitle: "Who we are",
        aboutCompanyText1: "Eco Meister Haus is a team of professionals in energy-efficient home construction. We work with SIP technology and apply modern European standards at every stage — from design to key handover.",
        aboutCompanyText2: "Our goal is to build homes that are comfortable to live in and cost-effective to maintain. Warm in winter, cool in summer, durable and beautiful.",
        aboutValuesTitle: "Our principles",
        aboutValuesDesc: "Quality, ecology and European standards — in every project",
        val1Title: "Eco-friendly",
        val1Desc: "We use only safe, certified materials with no harmful emissions",
        val2Title: "Quality",
        val2Desc: "Every stage undergoes quality control. We don't hand over until we're sure of its reliability",
        val3Title: "European standards",
        val3Desc: "We build in accordance with European energy efficiency and construction regulations",
        aboutApproachTitle: "Our approach",
        aboutApproachDesc: "How we work with every client",
        approach1Title: "We listen and understand",
        approach1Desc: "We start with a detailed conversation about your wishes, budget and timeline. No template solutions.",
        approach2Title: "We design for you",
        approach2Desc: "We develop an individual project tailored to your plot, climate and lifestyle.",
        approach3Title: "We build transparently",
        approach3Desc: "You know every step. Regular reports, site photos, fixed budget with no hidden costs.",
        approach4Title: "We deliver turnkey",
        approach4Desc: "We hand over the finished home with a complete set of documents and a warranty.",
        aboutTechTitle: "Technologies and materials",
        aboutTechText1: "The foundation of our homes is SIP technology (Structural Insulated Panels). These are sandwich panels made of OSB and polystyrene foam, providing high thermal insulation, strength and construction speed.",
        aboutTechText2: "A SIP home is built several times faster than a brick one, while surpassing it in energy efficiency. Heating costs are reduced by up to 60%.",
        techStat1: "heating cost savings",
        techStat2: "faster than brick homes",
        techStat3: "years service life",
        techStat4: "energy efficiency class",
        aboutCtaTitle: "Ready to build your dream home?",
        aboutCtaDesc: "Tell us about your project — we'll find the optimal solution and calculate the cost",
        bank: "BANK DETAILS",
        social: "SOCIAL MEDIA",
        advIntro: "Eco Meister Haus builds energy-efficient homes using SIP technology in accordance with European standards. We take full responsibility for every stage — from design to keys — and offer transparent conditions with no hidden fees.",
        advFaqTitle: "Frequently Asked Questions",
        advFaq1Q: "How durable is a SIP house compared to a brick one?",
        advFaq1A: "SIP panels withstand loads comparable to brick walls, and in some compression and seismic tests, they outperform them. The construction has been proven by decades of operation in Europe and North America.",
        advFaq2Q: "How energy-efficient is a SIP house in winter?",
        advFaq2A: "Thanks to the monolithic layer of insulation without cold bridges, an A+ class house consumes 50–60% less energy for heating than a traditional house of the same area.",
        advFaq3Q: "Does the construction comply with European standards?",
        advFaq3A: "Yes. We use certified materials and work in accordance with European construction standards. All panels undergo quality control before being delivered to the site.",
        advCtaTitle: "Convinced of our advantages?",
        advCtaDesc: "Contact us — we'll discuss your project and show how these advantages work specifically for you"
    },
 
    ro: {
        lang: "Limbă",
        services: "Servicii",
        stages: "Etapele construcției",
        stagesDesc: "Proces complet de construcție a casei de la idee până la mutare",
        advantages: "Avantaje",
        projects: "Proiecte",
        contacts: "Contacte",
        question: "Aveți întrebări?",
        contact: "Contactați-ne",
        name: "Numele dvs.",
        email: "Emailul dvs.",
        phone: "Telefon",
        subject: "Subiect",
        message: "Mesajul dvs.",
        send: "Trimite",
        servicesTitle: "Serviciile noastre",
        servicesDesc: "Oferim servicii complete în domeniul construcțiilor.",
        service1: "Proiectare",
        service2: "Inginerie",
        service3: "Construcție",
        service1Desc: "Creăm proiecte moderne și eficiente.",
        learnMore: "Detalii",
        service2Desc: "Soluții inginerești complete.",
        service3Desc: "Ciclu complet de construcție.",
        stagesTitle: "Etapele construcției",
        stage1: "Pregătirea terenului și fundația",
        stage1Desc: "Nivelare, excavare, fundație din beton",
        stage2: "Proiectare și inginerie",
        stage2Desc: "Proiect arhitectural și calcule",
        stage3: "Producția panourilor SIP",
        stage3Desc: "Fabricarea pereților, acoperișului și podelei",
        stage4: "Livrare și montaj",
        stage4Desc: "Asamblarea structurii pe șantier",
        stage5: "Acoperiș și exterior",
        stage5Desc: "Montaj acoperiș, ferestre și fațadă",
        stage6: "Sisteme inginerești",
        stage6Desc: "Electricitate, încălzire și apă",
        stage7: "Finisaje interioare",
        stage7Desc: "Pereți, podele, vopsire și echipamente",
        stage8: "Testare și inspecție",
        stage8Desc: "Verificarea sistemelor",
        stage9: "Predare și mutare",
        stage9Desc: "Predarea cheilor și documentelor",
        ctaStagesTitle: "Gata să construiți?",
        ctaStagesDesc: "Contactați-ne — vom discuta proiectul și vom calcula costul",
        ctaContact: "Obțineți consultație",
        ctaProjects: "Vedeți proiectele",
        ctaProjectsTitle: "Doriți o casă similară?",
        ctaProjectsDesc: "Vom discuta proiectul dvs. și vom găsi soluția optimă",
        advantagesTitle: "Avantajele noastre",
        advantagesDesc: "De ce clienții aleg Eco Haus Meister",
        adv1: "Ciclu complet de construcție",
        adv1Desc: "De la proiectare până la predare",
        adv2: "Construcție rapidă",
        adv2Desc: "Tehnologiile moderne reduc timpul",
        adv3: "Materiale ecologice",
        adv3Desc: "Soluții sigure și eficiente energetic",
        adv4: "Cost optim",
        adv4Desc: "Cel mai bun raport calitate-preț",
        adv5: "Tehnologii moderne",
        adv5Desc: "Folosim SIP și soluții inovatoare",
        adv6: "Abordare individuală",
        adv6Desc: "Ținem cont de toate cerințele clientului",
        projectsTitle: "Proiectele noastre",
        projectsDesc: "Descoperiți proiectele noastre realizate.",
        catModern: "Moderne",
        catCountry: "La țară",
        catMinimal: "Minimalism",
        catModernTitle: "Case moderne",
        catCountryTitle: "Case de țară",
        catMinimalTitle: "Case minimaliste",
        project1: "Casă modernă",
        project1Desc: "Casă eficientă energetic cu design modern.",
        project1Full: "Casă complet eficientă energetic construită cu panouri SIP.",
        project2: "Cabană de țară",
        project2Desc: "Casă confortabilă pentru familie în afara orașului.",
        project2Full: "Cabană spațioasă cu terasă și ferestre panoramice.",
        project3: "Casă minimalistă",
        project3Desc: "Casă elegantă în stil minimalist modern.",
        project3Full: "Minimalism modern cu planificare funcțională.",
        viewProject: "Vezi",
        heroTitle1: "Construim mai rapid, mai ușor și mai eficient",
        heroTitle2: "Tehnologii SIP moderne",
        heroTitle3: "Case fiabile și eficiente energetic",
        whyTitle: "De ce Eco Haus Meister",
        whyDesc: "Patru motive pentru care ne încredințează construcția casei",
        why1Title: "Rapid",
        why1Desc: "Casă la cheie în 3–6 luni datorită tehnologiei SIP",
        why2Title: "Ecologic",
        why2Desc: "Doar materiale certificate fără emisii nocive",
        why3Title: "Standarde europene",
        why3Desc: "Construim conform normelor europene de eficiență energetică",
        why4Title: "Individual",
        why4Desc: "Fiecare proiect — pentru clientul, terenul și bugetul specific",
        sipBadge: "Tehnologia viitorului",
        sipTitle: "SIP Premium Class — case de nouă generație",
        sipDesc: "Panourile SIP (Structural Insulated Panels) sunt o construcție din două plăci OSB cu un strat de polistiren expandat între ele. Rezultat: o casă care păstrează căldura iarna, răcoarea vara și se construiește de câteva ori mai repede decât una din cărămidă.",
        sipPoint1: "Clasa de eficiență energetică A+ — costuri de încălzire reduse cu până la 60%",
        sipPoint2: "Montajul casei — de la 2 până la 4 săptămâni",
        sipPoint3: "Durată de viață — peste 50 de ani fără pierderea proprietăților",
        sipPoint4: "Certificat conform standardelor europene",
        sipCta: "Aflați despre etapele construcției",
        sipStat1: "reducere costuri încălzire",
        sipStat2: "mai rapid decât casele din cărămidă",
        sipStat3: "ani durată de viață",
        sipStat4: "clasă de eficiență energetică",
        materialsTitle: "Materiale și tehnologii",
        materialsDesc: "Folosim doar ce a fost dovedit de practica europeană",
        mat1Title: "OSB + polistiren expandat",
        mat1Desc: "Inima panoului SIP — polistiren expandat de înaltă calitate între două plăci OSB. Asigură căldură, rigiditate și ușurință a structurii.",
        mat2Title: "Ventilație și climă",
        mat2Desc: "Recuperare de căldură, ventilație cu aport și evacuare și sisteme moderne de control al climei pentru un microclimat confortabil tot anul.",
        mat3Title: "Fațadă și acoperiș",
        mat3Desc: "Sisteme de fațadă durabile, țigle metalice și învelitori moi de la producători europeni. Protecție împotriva umidității, focului și UV.",
        stagesPreviewTitle: "Cum construim",
        stagesPreviewDesc: "De la primul apel până la predarea cheilor — un proces clar fără surprize",
        stagesPrev1: "Teren și fundație",
        stagesPrev2: "Proiect și panouri",
        stagesPrev3: "Asamblare și acoperiș",
        stagesPrev4: "Finisaje și mutare",
        stagesPreviewCta: "Toate etapele în detaliu →",
        projectsPreviewTitle: "Proiectele noastre",
        projectsPreviewDesc: "Case realizate — de la compacte la spațioase",
        projectsPreviewCta: "Vezi toate proiectele →",
        designBadge: "Doar pentru dvs.",
        designTitle: "Design individual pentru stilul dvs. de viață",
        designDesc: "Nu vindem cutii standard. Fiecare casă este proiectată pentru o persoană specifică — ținând cont de teren, familie, obiceiuri și buget. Alegeți planul, fațada, materialele de finisare și stilul interior.",
        designPoint1: "Plan liber",
        designPoint2: "Alegerea fațadei și acoperișului",
        designPoint3: "Orice stil interior",
        designPoint4: "Adaptat la terenul dvs.",
        designCta: "Discutați proiectul",
        ctaBadge: "Începeți astăzi",
        ctaMainTitle: "Gata să construiți casa visurilor dvs.?",
        ctaMainDesc: "Spuneți-ne despre proiectul dvs. — vom calcula costul, vom propune o soluție și vom răspunde la toate întrebările. Gratuit și fără obligații.",
        ctaMainBtn1: "Obțineți consultație",
        ctaMainBtn2: "Vedeți proiectele",
        aboutTitle: "Despre compania noastră",
        aboutDesc: "Suntem specializați în construcția caselor eficiente energetic folosind tehnologia SIP.",
        about: "Despre noi",
        aboutHeroTitle: "Despre noi",
        aboutHeroDesc: "Construim case moderne, fiabile și eficiente energetic conform standardelor europene",
        aboutCompanyTitle: "Cine suntem",
        aboutCompanyText1: "Eco Meister Haus este o echipă de profesioniști în construcția caselor eficiente energetic. Lucrăm cu tehnologia SIP și aplicăm standarde europene moderne la fiecare etapă — de la proiectare până la predarea cheilor.",
        aboutCompanyText2: "Scopul nostru este să construim case în care să fie confortabil de trăit și rentabil de întreținut. Calde iarna, răcoroase vara, durabile și frumoase.",
        aboutValuesTitle: "Principiile noastre",
        aboutValuesDesc: "Calitate, ecologie și standarde europene — în fiecare proiect",
        val1Title: "Ecologic",
        val1Desc: "Folosim doar materiale sigure, certificate, fără emisii nocive",
        val2Title: "Calitate",
        val2Desc: "Fiecare etapă trece prin control de calitate. Nu predăm obiectul până nu suntem siguri de fiabilitatea sa",
        val3Title: "Standarde europene",
        val3Desc: "Construim conform normelor europene de eficiență energetică și reglementărilor de construcție",
        aboutApproachTitle: "Abordarea noastră",
        aboutApproachDesc: "Cum lucrăm cu fiecare client",
        approach1Title: "Ascultăm și înțelegem",
        approach1Desc: "Începem cu o conversație detaliată despre dorințele, bugetul și termenele dvs. Fără soluții șablon.",
        approach2Title: "Proiectăm pentru dvs.",
        approach2Desc: "Dezvoltăm un proiect individual adaptat terenului, climei și stilului dvs. de viață.",
        approach3Title: "Construim transparent",
        approach3Desc: "Știți fiecare pas. Rapoarte regulate, fotografii de pe șantier, deviz fix fără costuri ascunse.",
        approach4Title: "Predăm la cheie",
        approach4Desc: "Predăm casa finalizată cu un pachet complet de documente și garanție.",
        aboutTechTitle: "Tehnologii și materiale",
        aboutTechText1: "La baza caselor noastre stă tehnologia SIP (Structural Insulated Panels). Acestea sunt panouri sandwich din OSB și polistiren expandat, care asigură o izolație termică ridicată, rezistență și viteză de construcție.",
        aboutTechText2: "O casă SIP se construiește de mai multe ori mai rapid decât una din cărămidă, depășind-o în eficiență energetică. Costurile de încălzire scad cu până la 60%.",
        techStat1: "economii la încălzire",
        techStat2: "mai rapid decât casele din cărămidă",
        techStat3: "ani durată de viață",
        techStat4: "clasă de eficiență energetică",
        aboutCtaTitle: "Gata să construiți casa visurilor dvs.?",
        aboutCtaDesc: "Spuneți-ne despre proiectul dvs. — vom găsi soluția optimă și vom calcula costul",
        bank: "DATE BANCARE",
        social: "REȚELE SOCIALE",
        advIntro: "Eco Meister Haus construiește case eficiente energetic folosind tehnologia SIP în conformitate cu standardele europene. Ne asumăm responsabilitatea completă pentru fiecare etapă — de la proiectare până la chei — și oferim condiții transparente fără costuri ascunse.",
        advFaqTitle: "Întrebări frecvente",
        advFaq1Q: "Cât de durabilă este o casă SIP comparativ cu una din cărămidă?",
        advFaq1A: "Panourile SIP rezistă la sarcini comparabile cu pereții din cărămidă și, în unele teste de compresie și seismice, le depășesc. Construcția a fost dovedită de decenii de operare în Europa și America de Nord.",
        advFaq2Q: "Cât de eficientă energetic este o casă SIP iarna?",
        advFaq2A: "Datorită stratului monolitic de izolație fără punți termice, o casă de clasa A+ consumă cu 50–60% mai puțină energie pentru încălzire decât o casă tradițională de aceeași suprafață.",
        advFaq3Q: "Construcția respectă standardele europene?",
        advFaq3A: "Da. Folosim materiale certificate și lucrăm în conformitate cu standardele europene de construcție. Toate panourile trec prin controlul calității înainte de a fi livrate pe șantier.",
        advCtaTitle: "Convins de avantajele noastre?",
        advCtaDesc: "Contactați-ne — vom discuta despre proiectul dvs. și vom arăta cum funcționează aceste avantaje specific pentru dvs."
    },
 
    de: {
        lang: "Sprache",
        services: "Dienstleistungen",
        stages: "Bauphasen",
        stagesDesc: "Kompletter Bauprozess vom Konzept bis zum Einzug",
        advantages: "Vorteile",
        projects: "Projekte",
        contacts: "Kontakte",
        question: "Haben Sie Fragen?",
        contact: "Kontaktieren Sie uns",
        name: "Ihr Name",
        email: "Ihre E-Mail",
        phone: "Telefon",
        subject: "Betreff",
        message: "Ihre Nachricht",
        send: "Senden",
        servicesTitle: "Unsere Dienstleistungen",
        servicesDesc: "Wir bieten umfassende Bauleistungen an.",
        service1: "Planung",
        service2: "Ingenieurwesen",
        service3: "Bau",
        service1Desc: "Wir erstellen moderne und effiziente Hausprojekte.",
        learnMore: "Mehr erfahren",
        service2Desc: "Ingenieurlösungen.",
        service3Desc: "Vollständiger Bauzyklus.",
        stagesTitle: "Bauphasen",
        stage1: "Grundstücksvorbereitung & Fundament",
        stage1Desc: "Nivellierung, Aushub, Betonfundament",
        stage2: "Planung & Ingenieurwesen",
        stage2Desc: "Architektur und Berechnungen",
        stage3: "SIP-Paneele Produktion",
        stage3Desc: "Herstellung von Wänden, Dach und Boden",
        stage4: "Lieferung & Montage",
        stage4Desc: "Montage der Hausstruktur vor Ort",
        stage5: "Dach & Außenarbeiten",
        stage5Desc: "Dach, Fenster und Fassade",
        stage6: "Technische Systeme",
        stage6Desc: "Elektrik, Heizung und Sanitär",
        stage7: "Innenausbau",
        stage7Desc: "Wände, Böden, Anstrich und Ausstattung",
        stage8: "Prüfung & Inspektion",
        stage8Desc: "Systemtests und Kontrolle",
        stage9: "Übergabe & Einzug",
        stage9Desc: "Schlüsselübergabe und Dokumente",
        ctaStagesTitle: "Bereit zu bauen?",
        ctaStagesDesc: "Kontaktieren Sie uns — wir besprechen Ihr Projekt und berechnen die Kosten",
        ctaContact: "Beratung erhalten",
        ctaProjects: "Projekte ansehen",
        ctaProjectsTitle: "Möchten Sie ein ähnliches Haus?",
        ctaProjectsDesc: "Wir besprechen Ihr Projekt und finden die optimale Lösung",
        advantagesTitle: "Unsere Vorteile",
        advantagesDesc: "Warum Kunden Eco Haus Meister wählen",
        adv1: "Kompletter Bauzyklus",
        adv1Desc: "Von der Planung bis zur schlüsselfertigen Übergabe",
        adv2: "Schnelle Bauzeit",
        adv2Desc: "Moderne Technologien verkürzen die Bauzeit",
        adv3: "Umweltfreundliche Materialien",
        adv3Desc: "Sichere und energieeffiziente Lösungen",
        adv4: "Optimale Kosten",
        adv4Desc: "Bestes Preis-Leistungs-Verhältnis",
        adv5: "Moderne Technologien",
        adv5Desc: "Wir nutzen SIP und innovative Lösungen",
        adv6: "Individuelle Herangehensweise",
        adv6Desc: "Wir berücksichtigen alle Kundenwünsche",
        projectsTitle: "Unsere Projekte",
        projectsDesc: "Entdecken Sie unsere realisierten Bauprojekte.",
        catModern: "Modern",
        catCountry: "Landhaus",
        catMinimal: "Minimalistisch",
        catModernTitle: "Moderne Häuser",
        catCountryTitle: "Landhäuser",
        catMinimalTitle: "Minimalistische Häuser",
        project1: "Modernes Haus",
        project1Desc: "Energieeffizientes Haus mit modernem Design.",
        project1Full: "Vollständig energieeffizientes Haus mit SIP-Paneelen.",
        project2: "Landhaus",
        project2Desc: "Gemütliches Haus für eine Familie außerhalb der Stadt.",
        project2Full: "Geräumiges Haus mit Terrasse und Panoramafenstern.",
        project3: "Minimalistisches Haus",
        project3Desc: "Stilvolles Haus im modernen minimalistischen Design.",
        project3Full: "Moderner Minimalismus mit funktionalem Grundriss.",
        viewProject: "Ansehen",
        heroTitle1: "Schneller, einfacher und effizienter bauen",
        heroTitle2: "Moderne SIP-Technologien",
        heroTitle3: "Zuverlässige und energieeffiziente Häuser",
        whyTitle: "Warum Eco Haus Meister",
        whyDesc: "Vier Gründe, warum uns Menschen den Bau ihres Hauses anvertrauen",
        why1Title: "Schnell",
        why1Desc: "Schlüsselfertiges Haus in 3–6 Monaten dank SIP-Technologie",
        why2Title: "Umweltfreundlich",
        why2Desc: "Nur zertifizierte Materialien ohne Schadstoffe",
        why3Title: "Europäische Standards",
        why3Desc: "Wir bauen nach europäischen Energieeffizienznormen",
        why4Title: "Individuell",
        why4Desc: "Jedes Projekt — für den spezifischen Kunden, Grundstück und Budget",
        sipBadge: "Technologie der Zukunft",
        sipTitle: "SIP Premium Class — Häuser der nächsten Generation",
        sipDesc: "SIP-Paneele (Structural Insulated Panels) sind eine Konstruktion aus zwei OSB-Platten mit einer Polystyrolschaumschicht dazwischen. Ergebnis: Ein Haus, das im Winter warm, im Sommer kühl bleibt und mehrmals schneller als ein Ziegelhaus gebaut wird.",
        sipPoint1: "Energieeffizienzklasse A+ — Heizkosten um bis zu 60% reduziert",
        sipPoint2: "Hausmontage — von 2 bis 4 Wochen",
        sipPoint3: "Lebensdauer — über 50 Jahre ohne Eigenschaftsverlust",
        sipPoint4: "Nach europäischen Standards zertifiziert",
        sipCta: "Mehr über Bauphasen erfahren",
        sipStat1: "Heizkosteneinsparung",
        sipStat2: "schneller als Ziegelhäuser",
        sipStat3: "Jahre Lebensdauer",
        sipStat4: "Energieeffizienzklasse",
        materialsTitle: "Materialien und Technologien",
        materialsDesc: "Wir verwenden nur das, was durch europäische Praxis bewährt ist",
        mat1Title: "OSB + Polystyrolschaum",
        mat1Desc: "Das Herz der SIP-Platte — hochwertiger Polystyrolschaum zwischen zwei OSB-Platten. Bietet Wärme, Steifigkeit und leichte Konstruktion.",
        mat2Title: "Lüftung und Klima",
        mat2Desc: "Wärmerückgewinnung, Zu- und Abluftanlage und moderne Klimasteuerungssysteme für ein komfortables Raumklima das ganze Jahr über.",
        mat3Title: "Fassade und Dach",
        mat3Desc: "Langlebige Fassadensysteme, Metallziegel und Weichdächer von europäischen Herstellern. Schutz vor Feuchtigkeit, Feuer und UV.",
        stagesPreviewTitle: "Wie wir bauen",
        stagesPreviewDesc: "Vom ersten Anruf bis zur Schlüsselübergabe — ein klarer Prozess ohne Überraschungen",
        stagesPrev1: "Grundstück und Fundament",
        stagesPrev2: "Planung und Paneele",
        stagesPrev3: "Montage und Dach",
        stagesPrev4: "Ausbau und Einzug",
        stagesPreviewCta: "Alle Phasen im Detail →",
        projectsPreviewTitle: "Unsere Projekte",
        projectsPreviewDesc: "Fertiggestellte Häuser — von kompakt bis geräumig",
        projectsPreviewCta: "Alle Projekte ansehen →",
        designBadge: "Nur für Sie",
        designTitle: "Individuelles Design für Ihren Lebensstil",
        designDesc: "Wir verkaufen keine Standardboxen. Jedes Haus wird für eine bestimmte Person entworfen — unter Berücksichtigung von Grundstück, Familie, Gewohnheiten und Budget. Sie wählen Grundriss, Fassade, Ausbaumaterialien und Einrichtungsstil.",
        designPoint1: "Freier Grundriss",
        designPoint2: "Wahl von Fassade und Dach",
        designPoint3: "Jeder Einrichtungsstil",
        designPoint4: "An Ihr Grundstück angepasst",
        designCta: "Projekt besprechen",
        ctaBadge: "Starten Sie heute",
        ctaMainTitle: "Bereit, Ihr Traumhaus zu bauen?",
        ctaMainDesc: "Erzählen Sie uns von Ihrem Projekt — wir berechnen die Kosten, schlagen eine Lösung vor und beantworten alle Fragen. Kostenlos und unverbindlich.",
        ctaMainBtn1: "Beratung erhalten",
        ctaMainBtn2: "Projekte ansehen",
        aboutTitle: "Über unser Unternehmen",
        aboutDesc: "Wir sind auf den Bau energieeffizienter Häuser mit SIP-Technologie spezialisiert.",
        about: "Über uns",
        aboutHeroTitle: "Über uns",
        aboutHeroDesc: "Wir bauen moderne, zuverlässige und energieeffiziente Häuser nach europäischen Standards",
        aboutCompanyTitle: "Wer wir sind",
        aboutCompanyText1: "Eco Meister Haus ist ein Team von Fachleuten im Bereich des energieeffizienten Hausbaus. Wir arbeiten mit SIP-Technologie und wenden moderne europäische Standards in jeder Phase an — von der Planung bis zur Schlüsselübergabe.",
        aboutCompanyText2: "Unser Ziel ist es, Häuser zu bauen, in denen es angenehm zu leben und kostengünstig zu unterhalten ist. Im Winter warm, im Sommer kühl, langlebig und schön.",
        aboutValuesTitle: "Unsere Grundsätze",
        aboutValuesDesc: "Qualität, Ökologie und europäische Standards — in jedem Projekt",
        val1Title: "Umweltfreundlich",
        val1Desc: "Wir verwenden nur sichere, zertifizierte Materialien ohne Schadstoffe",
        val2Title: "Qualität",
        val2Desc: "Jede Phase durchläuft eine Qualitätskontrolle. Wir übergeben erst, wenn wir von der Zuverlässigkeit überzeugt sind",
        val3Title: "Europäische Standards",
        val3Desc: "Wir bauen gemäß europäischen Energieeffizienz- und Bauvorschriften",
        aboutApproachTitle: "Unsere Herangehensweise",
        aboutApproachDesc: "Wie wir mit jedem Kunden arbeiten",
        approach1Title: "Wir hören zu und verstehen",
        approach1Desc: "Wir beginnen mit einem ausführlichen Gespräch über Ihre Wünsche, Budget und Zeitplan. Keine Standardlösungen.",
        approach2Title: "Wir planen für Sie",
        approach2Desc: "Wir entwickeln ein individuelles Projekt, das auf Ihr Grundstück, Klima und Lebensstil zugeschnitten ist.",
        approach3Title: "Wir bauen transparent",
        approach3Desc: "Sie kennen jeden Schritt. Regelmäßige Berichte, Fotos vom Objekt, fester Kostenvoranschlag ohne versteckte Kosten.",
        approach4Title: "Wir liefern schlüsselfertig",
        approach4Desc: "Wir übergeben das fertige Haus mit vollständigen Unterlagen und Garantie.",
        aboutTechTitle: "Technologien und Materialien",
        aboutTechText1: "Die Grundlage unserer Häuser ist die SIP-Technologie (Structural Insulated Panels). Das sind Sandwichplatten aus OSB und Polystyrolschaum, die hohe Wärmedämmung, Festigkeit und Baugeschwindigkeit bieten.",
        aboutTechText2: "Ein SIP-Haus wird mehrmals schneller als ein Ziegelhaus gebaut und übertrifft es in der Energieeffizienz. Die Heizkosten sinken um bis zu 60%.",
        techStat1: "Heizkosteneinsparung",
        techStat2: "schneller als Ziegelhäuser",
        techStat3: "Jahre Lebensdauer",
        techStat4: "Energieeffizienzklasse",
        aboutCtaTitle: "Bereit, Ihr Traumhaus zu bauen?",
        aboutCtaDesc: "Erzählen Sie uns von Ihrem Projekt — wir finden die optimale Lösung und berechnen die Kosten",
        bank: "BANKDATEN",
        social: "SOZIALE MEDIEN",
        advIntro: "Eco Meister Haus baut energieeffiziente Häuser mit SIP-Technologie nach europäischen Standards. Wir übernehmen die volle Verantwortung für jede Phase — von der Planung bis zu den Schlüsseln — und bieten transparente Bedingungen ohne versteckte Kosten.",
        advFaqTitle: "Häufig gestellte Fragen",
        advFaq1Q: "Wie langlebig ist ein SIP-Haus im Vergleich zu einem Ziegelhaus?",
        advFaq1A: "SIP-Paneele halten Belastungen stand, die mit Ziegelwänden vergleichbar sind, und übertreffen sie in einigen Druck- und Erdbebentests. Die Konstruktion hat sich durch jahrzehntelangen Betrieb in Europa und Nordamerika bewährt.",
        advFaq2Q: "Wie energieeffizient ist ein SIP-Haus im Winter?",
        advFaq2A: "Dank der monolithischen Dämmschicht ohne Kältebrücken verbraucht ein Haus der Klasse A+ 50–60% weniger Energie für die Heizung als ein traditionelles Haus gleicher Fläche.",
        advFaq3Q: "Entspricht die Konstruktion europäischen Standards?",
        advFaq3A: "Ja. Wir verwenden zertifizierte Materialien und arbeiten gemäß den europäischen Bauvorschriften. Alle Paneele durchlaufen eine Qualitätskontrolle, bevor sie auf die Baustelle geliefert werden.",
        advCtaTitle: "Überzeugt von unseren Vorteilen?",
        advCtaDesc: "Kontaktieren Sie uns — wir besprechen Ihr Projekt und zeigen Ihnen, wie diese Vorteile genau für Sie funktionieren",
    }
};


function toggleLang() {
    const menu = document.getElementById("langMenu");
    if (menu) menu.classList.toggle("hidden");
}

function setLang(lang) {
    const currentLangMobile = document.getElementById("currentLangMobile");
    const currentLang = document.getElementById("currentLang");

    if (translations[lang]) {
        if (currentLangMobile) {
            currentLangMobile.innerText = translations[lang].lang;
        }

        if (currentLang) {
            currentLang.innerText = translations[lang].lang;
        }
    }

    const elements = document.querySelectorAll("[data-key]");
    elements.forEach(el => {
        const key = el.getAttribute("data-key");
        if (translations[lang][key]) {
            if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
                el.placeholder = translations[lang][key];
            } else {
                el.innerText = translations[lang][key];
            }
        }
    });

    const langMenu = document.getElementById("langMenu");
    if (langMenu) langMenu.classList.add("hidden");

    localStorage.setItem("lang", lang);
}

function openModal(id) {
    const modal = document.getElementById(id);
    if (modal) {
        modal.classList.remove("hidden");
        modal.classList.add("flex");
    }
}

function closeModal(id) {
    const modal = document.getElementById(id);
    if (modal) modal.classList.add("hidden");
}

function toggleMenu() {
    const mobileMenu = document.getElementById("mobileMenu");
    if (mobileMenu) mobileMenu.classList.toggle("hidden");
}

document.addEventListener("DOMContentLoaded", () => {
    // Язык
    const savedLang = localStorage.getItem("lang") || "ru";
    setLang(savedLang);

    // === Слайдер ===
    let currentSlide = 0;
    const slides = document.querySelectorAll(".slide");
    const dots = document.querySelectorAll(".dot");
    const prevBtn = document.getElementById("prevSlide");
    const nextBtn = document.getElementById("nextSlide");

    function showSlide(index) {
        // 1. Скрыть все слайды
        slides.forEach(slide => slide.classList.add("hidden"));

        // 2. Сбросить стили у ВСЕХ точек (безопасно, даже если точек нет)
        dots.forEach(dot => {
            dot.classList.remove("bg-white");
            dot.classList.add("bg-white/50");
        });

        // 3. Показать нужный слайд
        if (slides[index]) slides[index].classList.remove("hidden");

        // 4. Активировать точку, если она существует
        if (dots[index]) dots[index].classList.add("bg-white");
    }

    function nextSlide() {
        if (slides.length === 0) return;
        currentSlide = (currentSlide + 1) % slides.length;
        showSlide(currentSlide);
    }

    function prevSlide() {
        if (slides.length === 0) return;
        currentSlide = (currentSlide - 1 + slides.length) % slides.length;
        showSlide(currentSlide);
    }

    if (nextBtn) nextBtn.addEventListener("click", nextSlide);
    if (prevBtn) prevBtn.addEventListener("click", prevSlide);

    dots.forEach((dot, i) => {
        dot.addEventListener("click", () => {
            currentSlide = i;
            showSlide(i);
        });
    });

    if (slides.length) showSlide(0);

    // === Тач-свайп для мобильных ===
    const sliderEl = document.getElementById("slider");
    if (sliderEl) {
        let touchStartX = 0;

        // Скрыть кнопки на тач-устройствах
        if (window.matchMedia("(hover: none) and (pointer: coarse)").matches) {
            if (prevBtn) prevBtn.style.display = "none";
            if (nextBtn) nextBtn.style.display = "none";
        }

        sliderEl.addEventListener("touchstart", (e) => {
            touchStartX = e.changedTouches[0].clientX;
        }, { passive: true });

        sliderEl.addEventListener("touchend", (e) => {
            const delta = e.changedTouches[0].clientX - touchStartX;
            if (Math.abs(delta) < 50) return;
            if (delta < 0) {
                nextSlide();
            } else {
                prevSlide();
            }
        }, { passive: true });
    }
});

function toggleFaq(btn) {
            const answer = btn.nextElementSibling;
            const icon = btn.querySelector('.faq-icon');
            answer.classList.toggle('hidden');
            icon.textContent = answer.classList.contains('hidden') ? '+' : '−';
        }